PeminjamanRuanganSarpras/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^peminjam/', include('peminjam.urls')),
    url(r'^peminjaman/', include('peminjaman.urls')),
    url(r'^ruangan/', include('ruangan.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^login/$', auth_views.login, kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={'next_page': '/login/'}, name='logout'),
    url(r'^$', RedirectView.as_view(pattern_name='peminjaman:kalender_umum', permanent=False), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#    url(r'^admin/', admin.site.urls),

log/urls.py
from django.conf.urls import url
from . import views

app_name = 'log'

urlpatterns = [

    # /log/
    url(r'^$', views.index, name='index'),

    # /log/json/2016/
    url(r'^json/$', views.fetchrecord, name='jsonbase'),
    url(r'^json/(?P<start_year>[0-9]+)/$', views.fetchrecord, name='json'),

    # /log/filter/2017/1
    url(r'^filter/$', views.filter, name='filterbase'),
    url(r'^filter/(?P<select_year>[0-9]+)/(?P<select_month>[0-9]+)/', views.filter, name='filter'),
]

peminjam/urls.py
from django.conf.urls import url
from . import views

app_name = 'peminjam'

urlpatterns = [

    # /peminjam/
    url(r'^$', views.index, name='index'),

    # /peminjam/add/
    url(r'^add/$',views.formadd, name='add'),

    # /peminjam/edit/4
    url(r'^edit/$', views.formedit, name='editbase'),
    url(r'^edit/(?P<peminjam_id>[0-9]+)/$', views.formedit, name='edit'),

    # /peminjam/delete/4
    url(r'^delete/$', views.formdelete, name='deletebase'),
    url(r'^delete/(?P<peminjam_id>[0-9]+)/$', views.formdelete, name='delete'),

    # /peminjam/fetchjson/
    url(r'^json/$', views.fetchrecord, name='json'),
]

peminjaman/urls.py
from django.conf.urls import url
from . import views

app_name = 'peminjaman'

urlpatterns = [

    # /peminjaman/
    url(r'^$', views.index, name='index'),

    # /peminjaman/kalender
    url(r'^kalender/$', views.kalender, name='kalender'),
    url(r'^kalender-umum/$', views.kalender_umum, name='kalender_umum'),

    # /peminjaman/add/
    url(r'^add/$',views.formadd, name='add'),

    # /peminjaman/edit/4
    url(r'^edit/$', views.formedit, name='editbase'),
    url(r'^edit/(?P<peminjaman_id>[0-9]+)/$', views.formedit, name='edit'),

    # /peminjaman/delete/4
    url(r'^delete/$', views.formdelete, name='deletebase'),
    url(r'^delete/(?P<peminjaman_id>[0-9]+)/$', views.formdelete, name='delete'),

    # /peminjaman/json/2016
    url(r'^json/$', views.fetchrecord, name='jsonbase'),
    url(r'^json/(?P<start_year>[0-9]+)/$', views.fetchrecord, name='json'),

    # /peminjaman/json_umum/2016
    url(r'^json_umum/$', views.fetchrecord_umum, name='jsonbase_umum'),
    url(r'^json_umum/(?P<start_year>[0-9]+)/$', views.fetchrecord_umum, name='json_umum'),

    # /peminjaman/bayar/2
    url(r'^bayar/$', views.togglepembayaran, name='bayarbase'),
    url(r'^bayar/(?P<peminjaman_id>[0-9]+)/$', views.togglepembayaran, name='bayar'),

    #/peminjaman/filter/2017
    url(r'^filter/$', views.filter, name='filter_base'),
    url(r'^filter/(?P<year>[0-9]+)/$', views.filter, name='filter'),
]

ruangan/urls.py
from django.conf.urls import url
from . import views

app_name = 'ruangan'

urlpatterns = [

    # /ruangan/
    url(r'^$', views.index, name='index'),

    # /ruangan/add/
    url(r'^add/$', views.formadd, name='add'),

    # /ruangan/edit/4
    url(r'^edit/$', views.formedit, name='editbase'),
    url(r'^edit/(?P<ruangan_id>[0-9]+)/$', views.formedit, name='edit'),

    # /ruangan/delete/4
    url(r'^delete/$', views.formdelete, name='deletebase'),
    url(r'^delete/(?P<ruangan_id>[0-9]+)/$', views.formdelete, name='delete'),

    # /ruangan/json/
    url(r'^json/$', views.fetchrecord, name='json'),

    # /ruangan/json_umum/
    url(r'^json_umum/$', views.fetchrecord_umum, name='json_umum'),
]

admin_sarpras/models.py
from django.db import models

# Create your models here.

admin_sarpras/views.py
from django.shortcuts import render

# Create your views here.

admin_sarpras/templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'api/rCalendar/css/calendar.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>
    <script src="{% static 'api/rCalendar/js/calendar.js' %}"></script>
    <script src="{% static 'api/rCalendar/js/calendarCostum.js' %}"></script>

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
    <script src="{% static 'js/ui-bootstrap-custom-tpls-2.5.0.min.js' %}" ></script>


    <!-- Disable Native Chrome Datepicker -->
    <style>
    input::-webkit-calendar-picker-indicator{
        display: none;
    }
    </style>

    {% block head %}
    <title>SB Admin - Bootstrap Admin Template</title>
    {% endblock %}


</head>

<body>

    <div class="navbar-fixed-top">
        <nav class="navbar navbar-inverse" style="border-radius:0px">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div>
	          <img src='{% static "images/itb.png" %}' alt="Logo ITB" style="height: 50px; margin: 7px;float: left">
	          <a class="navbar-brand" href="#">Admin Ruangan</a>
          </div>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
          <ul class="nav navbar-nav side-nav">
            <li id="kalenderPeminjaman">
                <a href="{% url 'peminjaman:kalender' %}"><i>&#xe800;</i> Kalender</a>
            </li>
            <li id="peminjaman">
                <a href="{% url 'peminjaman:index' %}"><i>&#xe802;</i>Peminjaman</a>
            </li>
            <li id="peminjam">
                <a href="{% url 'peminjam:index' %}"><i>&#xe801;</i> Peminjam</a>
            </li>
            <li id="ruangan">
                <a href="{% url 'ruangan:index' %}"><i>&#xe804;</i> Ruangan</a>
            </li>
            <li id="log">
                <a href="{% url 'log:index' %}"><i>&#xe804;</i> Log</a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'logout' %}"><i>&#xe803;</i> Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    </div>
    <div id="page-wrapper" style="min-height: 100vh">
        <div class="container-fluid">
            {% block body %}
            <br>
            <br>
            <br>
            <br>
            <br>
            {% endblock %}
        </div>
    </div>
</body>
</html>

admin_sarpras/templates/login.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>

    <title>Login</title>

</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class=" col-lg-offset-4 col-lg-4" >
                <div class="panel panel-primary" style="position: relative; transform: translateY(50%);">
                    <div class="panel-heading">
                        <h3 class="panel-title">Admin Peminjaman Login</h3>
                    </div>
                    <div class="panel-body">
                        <form action="{% url 'login' %}" method="post" accept-charset="utf-8" class="form-horizontal">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="col-md-offset-1 col-md-10">
                                    <label for="id_username" class="control-label">Nama pengguna</label>
                                    <input autofocus="" id="id_username" maxlength="254" name="username"
                                           type="text" class="form-control" required />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-1 col-md-10">
                                    <label for="id_password" class="control-label">Sandi</label>
                                    <input id="id_password" name="password" type="password" class="form-control" required />
                                </div>
                            </div>

                            {% for error_item in form.errors %}
                                <li>{{ error_item }}</li>
                            {% endfor %}

                            <input type="hidden" name="next" value="{% if input_peminjam %}{{ next }}{% else %}{% url 'peminjaman:index' %}{% endif %}" />
                            <div class="col-md-offset-1 col-md-10" style="text-align: right;padding-right: 2px">
                                <input class="btn-sm btn btn-primary" type="submit" value="Submit"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>