PeminjamanRuanganSarpras/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^peminjam/', include('peminjam.urls')),
    url(r'^peminjaman/', include('peminjaman.urls')),
    url(r'^ruangan/', include('ruangan.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^login/$', auth_views.login, kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={'next_page': '/login/'}, name='logout'),
    url(r'^$', RedirectView.as_view(pattern_name='peminjaman:kalender_umum', permanent=False), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#    url(r'^admin/', admin.site.urls),

log/urls.py
from django.conf.urls import url
from . import views

app_name = 'log'

urlpatterns = [

    # /log/
    url(r'^$', views.index, name='index'),

    # /log/json/2016/
    url(r'^json/$', views.fetchrecord, name='jsonbase'),
    url(r'^json/(?P<start_year>[0-9]+)/$', views.fetchrecord, name='json'),

    # /log/filter/2017/1
    url(r'^filter/$', views.filter, name='filterbase'),
    url(r'^filter/(?P<select_year>[0-9]+)/(?P<select_month>[0-9]+)/', views.filter, name='filter'),
]

ruangan/urls.py
from django.conf.urls import url
from . import views

app_name = 'ruangan'

urlpatterns = [

    # /ruangan/
    url(r'^$', views.index, name='index'),

    # /ruangan/add/
    url(r'^add/$', views.formadd, name='add'),

    # /ruangan/edit/4
    url(r'^edit/$', views.formedit, name='editbase'),
    url(r'^edit/(?P<ruangan_id>[0-9]+)/$', views.formedit, name='edit'),

    # /ruangan/delete/4
    url(r'^delete/$', views.formdelete, name='deletebase'),
    url(r'^delete/(?P<ruangan_id>[0-9]+)/$', views.formdelete, name='delete'),

    # /ruangan/json/
    url(r'^json/$', views.fetchrecord, name='json'),

    # /ruangan/json_umum/
    url(r'^json_umum/$', views.fetchrecord_umum, name='json_umum'),
]

ruangan/models.py
from django.db import models
from datetime import datetime
import os

def ruangan_foto_dir(instance, filename):
    if instance.id is None:
        try:
            nextid = (Ruangan.objects.latest('id')).id + 1
        except(Ruangan.DoesNotExist):
            nextid = 0
    else:
        nextid = instance.id

    fname, file_extension = os.path.splitext(filename)
    return 'ruangan/{0}_{1}{2}'.format(nextid, instance.nama, file_extension)

class Ruangan(models.Model):

    nama = models.CharField(max_length=250, unique=True, db_index=True)
    harga = models.BigIntegerField(default=0)
    deskripsi = models.CharField(max_length=1000, blank=True)

    RUANG = 'Ruang'
    SELASAR = 'Selasar'
    LAPANGAN = 'Lapangan'
    PILIHAN_TIPE_RUANG = (
        (RUANG, 'Ruang'),
        (SELASAR, 'Selasar'),
        (LAPANGAN, 'Lapangan'),
    )
    tipe = models.CharField(max_length=50, choices=PILIHAN_TIPE_RUANG, default=SELASAR)

    foto = models.ImageField(upload_to=ruangan_foto_dir, max_length=500, blank=True)
    restricted = models.BooleanField(default=False, db_index=True)

    warna = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.nama + ' - ' + self.tipe

ruangan/views.py
from django.shortcuts import render, redirect
from .models import Ruangan
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Ruangan index view, mostly for debugging purpose
@login_required
def index(request):
    all_ruangan = Ruangan.objects.all()
    return render(request, 'ruangan/index.html', {
        'all_ruangan': all_ruangan
    })


# Return a form which'll be used to add new Ruangan object to model
@login_required
def formadd(request):

	# Inisiasi variabel berdasarkan post jika ada
    new_nama = request.POST.get("nama",'')
    new_harga = request.POST.get("harga",0)
    new_deskripsi = request.POST.get("deskripsi", '')
    new_tipe = request.POST.get("tipe",'Selasar')
    new_warna = request.POST.get('warna', '#000000')
    if request.POST.get('restrict', False):
        new_restricted = True
    else:
        new_restricted = False

    error = []
    message = []

    # Jika ada data post yang diberikan,
    if request.method == 'POST':

        # Mengecek apakah ada nama valid yang diberikan
        if new_nama == '':
            error += ["Nama ruangan tidak boleh kosong", ]

        # Mengecek apakah tipe ruangan yg diberikan valid
        if (new_tipe != 'Selasar' and new_tipe != 'Lapangan' and new_tipe != 'Ruang'):
            error += ["Pilihan tipe tidak valid", ]

        # Mengecek apakah ada object dengan nama yang sama
        if (Ruangan.objects.filter(nama=new_nama)):
            error += ["Sudah ada data ruangan dengan nama yang sama", ]

        # Berusaha memasukan object ke database jika tidak ada error
        if not error:
            new_ruangan = Ruangan(
                nama = new_nama,
				harga = new_harga,
                deskripsi = new_deskripsi,
				tipe = new_tipe,
                warna = new_warna,
                restricted = new_restricted
            )
            if len(request.FILES) != 0:
                new_ruangan.foto = request.FILES['foto']
            else:
                new_ruangan.foto = None

            # Berusaha menyimpan perubahan dan redirect ke Index jika berhasil
            try:
                new_ruangan.save()
            except Exception as e:
                message += ["Unhandled Exception", ]
            else:
                return redirect(reverse('ruangan:index'))

    # Mengembalikan form yang sama
    return render(request, 'ruangan/add.html', {
        'error': error,
        'message': message,
        'nama': new_nama,
		'harga': new_harga,
        'deskripsi': new_deskripsi,
		'tipe': new_tipe,
        'warna': new_warna,
        'restrict' : new_restricted
    })


# Return a form which'll be used to edit Ruangan object to model
@login_required
def formedit(request, ruangan_id = 0):
	
	# Berusaha mendapat model ruangan yang ingin diubah
    try:
        selected_ruangan = Ruangan.objects.get(id=ruangan_id)
    except Exception as e:
        return redirect(reverse('ruangan:index'))

    # Inisiasi variabel berdasarkan post jika ada
    new_nama = request.POST.get("nama", '')
    new_harga = request.POST.get("harga", 0)
    new_deskripsi = request.POST.get("deskripsi", '')
    new_tipe = request.POST.get("tipe", 'Selasar')
    new_warna = request.POST.get('warna', '#000000')
    if request.POST.get('restrict', False):
        new_restricted = True
    else:
        new_restricted = False

    error = []
    message = []

    # Jika ada data post yang diberikan,
    if request.method == 'POST':

        # Mengecek apakah ada nama valid yang diberikan
        if new_nama == '':
            error += ["Nama ruangan tidak boleh kosong", ]

        # Mengecek apakah tipe ruangan yg diberikan valid
        if (new_tipe != 'Selasar' and new_tipe != 'Lapangan' and new_tipe != 'Ruang'):
            error += ["Pilihan tipe tidak valid", ]

        # Mengecek apakah ada object dengan nama yang sama
        if (Ruangan.objects.filter(nama=new_nama) and (not(selected_ruangan.nama == new_nama))):
            error += ["Sudah ada data peminjam dengan nama yang sama", ]

        # Berusaha mengubah informasi object jika tidak ada error
        if not error:
            selected_ruangan.nama = new_nama
            selected_ruangan.harga = new_harga
            selected_ruangan.deskripsi = new_deskripsi
            selected_ruangan.tipe = new_tipe
            selected_ruangan.warna = new_warna
            selected_ruangan.restricted = new_restricted
            if len(request.FILES) != 0:
                selected_ruangan.foto.delete()
                selected_ruangan.foto = request.FILES['foto']
			
            # Berusaha menyimpan perubahan dan redirect ke Index jika berhasil
            try:
                selected_ruangan.save()
            except Exception as e:
                message += ["Unhandled Exception", ]
                print(e)
            else:
                return redirect(reverse('ruangan:index'))


    # Mengembalikan form yang sama
    return render(request, 'ruangan/edit.html', {
        'selected_ruangan': selected_ruangan,
        'error': error,
        'message': message,
    })


# Return a form which'll be used to delete Ruangan object to model
@login_required
def formdelete(request, ruangan_id = 0):
    
	# Berusaha mendapat model peminjam yang ingin diubah
    try:
        selected_ruangan = Ruangan.objects.get(id=ruangan_id)
    except Exception as e:
        return redirect(reverse('ruangan:index'))

    # Inisiasi variabel berdasarkan post jika ada
    new_nama = request.POST.get("nama",'')
    error = []
    message = []

    # Jika ada data post yang diberikan,
    if(new_nama):

        # Mengecek apakah ada object dengan nama yang sama
        if (not(selected_ruangan.nama == new_nama)):
            error += ["Nama ruangan tidak sama", ]

        # Berusaha mengubah informasi object jika tidak ada error
        if not error:

            # Berusaha menyimpan perubahan dan redirect ke Index jika berhasil
            try:
                if selected_ruangan.foto:
                    selected_ruangan.foto.delete()
                selected_ruangan.delete()
            except Exception as e:
                message += ["Unhandled Exception", ]
            else:
                return redirect(reverse('ruangan:index'))

    # Mengembalikan form yang sama
    return render(request, 'ruangan/delete.html', {
        'selected_ruangan': selected_ruangan,
        'error': error,
        'message': message,
    })


@login_required
def fetchrecord(request):
    all_ruangan = Ruangan.objects.all().values()
    return JsonResponse({'results': list(all_ruangan)})


def fetchrecord_umum(request):
    all_ruangan = Ruangan.objects.filter(restricted=False).values()
    return JsonResponse({'results': list(all_ruangan)})

ruangan/templates/ruangan/add.html
{% extends "base.html" %}

{% block head %}
<title>Menambahkan Ruangan Baru</title>
{% endblock %}


{% block body %}
<div class="row">
	<div class="col-sm-8">
		<ul class="breadcrumb" style="margin-bottom: 10px;">
			<li><a href="{% url 'ruangan:index' %}">Ruangan</a></li>
			<li class="active">Tambah Ruangan</li>
		</ul>
	</div>
</div>
<div class="container-fluid">
<div class="row">
	<div class="col-lg-6 panel " >
		<form enctype="multipart/form-data" action="{% url 'ruangan:add' %}" method="post" id="ruangan_form" novalidate class="form-horizontal">
			{% csrf_token %}
			<fieldset>
				<legend style="padding-top: 15px;margin-bottom: 15px">Formulir Penambahan Ruangan</legend>
				<p style="color: red;text-align: right">* wajib diisi</p>
				<div class="form-group">
					<label for="id_nama" class="col-lg-3 control-label">Nama</label>
					<div class="col-lg-9">
						<div class="input-group">
							<input type="text" name="nama" id="id_nama" required value="{{ nama }}" maxlength="250" class="form-control"/>
							<span class="input-group-addon" style="font-size: 150%;color: red">*</span>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label for="id_harga" class="control-label col-lg-3">Harga</label>
					<div class="col-lg-9">
						<div class="input-group">
							<input type="number" name="harga" id="id_harga" required value="{{ harga }}" class="form-control"/>
							<span class="input-group-addon" style="font-size: 150%;color: red">*</span>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label for="id_deskripsi" class="control-label col-lg-3">Deskripsi</label>
					<div class="col-md-9">
						<textarea name="deskripsi" id="id_deskripsi" maxlength="1000" class="form-control">{{ deskripsi }}</textarea>
					</div>
				</div>

				<div class="form-group">
					<label for="id_tipe" class="control-label col-lg-3">Tipe</label>
					<div class="col-lg-9">
						<div class="input-group">
							<select name="tipe" id="id_tipe" class="form-control" required>
								<option value="Ruang" {% if tipe == "Ruang" %} selected {% endif %}>Ruang</option>
								<option value="Selasar" {% if tipe == "Selasar" %} selected {% endif %}>Selasar</option>
								<option value="Lapangan" {% if tipe == "Lapangan" %} selected {% endif %}>Lapangan</option>
							</select>
							<span class="input-group-addon" style="font-size: 150%;color: red">*</span>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label for="id_harga" class="control-label col-lg-3">Foto Ruangan</label>
					<div class="col-lg-9">
						<label class="btn btn-default btn-sm">
							Pilih Foto ...
							<input type="file" name="foto" style="display: none">
						</label>
					</div>
				</div>

				<div class="form-group">
					<label for="id_warna" class="control-label col-lg-3">Warna Ruangan</label>					
					<div class="col-lg-2">
						<div class="input-group" style="text-align: center">
							<label class="btn btn-default btn-sm">
								Pilih warna
								<input name="warna" id="id_warna" type="color" required class="form-control" ng-model="warna" />
							</label>
							<span class="input-group-addon" style="font-size: 150%;color: red;padding-left: 15px">*</span>
						</div>
					</div>					
				</div>

				<div class="form-group">
					<label for="id_restrict" class="control-label col-lg-3">Restrict Ruangan</label>
					<div class="col-lg-9">
						<div class="checkbox">
						  <label>
							  <input name="restrict" id="id_restrict" type="checkbox" {% if restrict %} checked {% endif %} > Ruangan disembunyikan <b style="color: red;padding-left: 5px">*</b>
						  </label>
						</div>
					</div>
				</div>
				<div class="form-group">
					<div class="col-lg-12" style="text-align: right">
						<input type="submit" value="Save" class="btn btn-primary"/>
						<a href="{% url 'ruangan:index' %}" class="btn btn-default">Cancel</a>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
	<div class="col-lg-4">
        {% if error %}
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Error</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        {% for error_item in error %}
                        <li>{{ error_item }}</li>
                        {% endfor %}

                        {% for message_item in message %}
                        <li>{{ message_item }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

ruangan/templates/ruangan/edit.html
{% extends "base.html" %}

{% block head %}
<title>Mengubah Informasi Ruangan</title>
{% endblock %}

{% block body %}
<div class="row">
	<div class="col-sm-8">
		<ul class="breadcrumb" style="margin-bottom: 10px;">
			<li><a href="{% url 'ruangan:index' %}">Ruangan</a></li>
			<li class="active">Ubah Ruangan</li>
		</ul>
	</div>
</div>
<div class="container-fluid">
<div class="row">
	<div class="col-lg-6 panel ">
		<form enctype="multipart/form-data" action="{% url 'ruangan:edit' selected_ruangan.id %}" method="post" id="ruangan_form" novalidate class="form-horizontal">
			{% csrf_token %}
			<fieldset>
				<legend style="padding-top: 15px;margin-bottom: 15px">Formulir Perubahan Ruangan</legend>
				<p style="color: red;text-align: right">* wajib diisi</p>
				<div class="form-group">
					<label for="id_nama" class="col-lg-3 control-label">Nama</label>
					<div class="col-lg-9">
						<div class="input-group">
							<input type="text" name="nama" id="id_nama" required value="{{ selected_ruangan.nama }}" maxlength="250" class="form-control"/>
							<span class="input-group-addon" style="font-size: 150%;color: red">*</span>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label for="id_harga" class="control-label col-lg-3">Harga</label>
					<div class="col-lg-9">
						<div class="input-group">
							<input type="number" name="harga" id="id_harga" required value="{{ selected_ruangan.harga }}" class="form-control"/>
							<span class="input-group-addon" style="font-size: 150%;color: red">*</span>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label for="id_deskripsi" class="control-label col-lg-3">Deskripsi</label>
					<div class="col-md-9">
						<textarea name="deskripsi" id="id_deskripsi" maxlength="1000" class="form-control">{{ selected_ruangan.deskripsi }}</textarea>
					</div>
				</div>

				<div class="form-group">
					<label for="id_tipe" class="control-label col-lg-3">Tipe</label>
					<div class="col-lg-9">
						<div class="input-group">
							<select name="tipe" id="id_tipe" class="form-control">
								<option value="Ruang" {% if selected_ruangan.tipe == "Ruang" %} selected {% endif %}>Ruang</option>
								<option value="Selasar" {% if selected_ruangan.tipe == "Selasar" %} selected {% endif %}>Selasar</option>
								<option value="Lapangan" {% if selected_ruangan.tipe == "Lapangan" %} selected {% endif %}>Lapangan</option>
							</select>
							<span class="input-group-addon" style="font-size: 150%;color: red">*</span>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label for="id_harga" class="control-label col-lg-3">Foto Ruangan</label>
					<div class="col-lg-9">
						<label class="btn btn-default btn-sm">
							Pilih Foto ...
							<input type="file" name="foto" style="display: none">
						</label>
					</div>
				</div>

				<div class="form-group">
					<label for="id_warna" class="control-label col-lg-3">Warna Ruangan</label>
					<div class="col-lg-2">
						<div class="input-group" style="text-align: center">
							<label class="btn btn-default btn-sm">
								Pilih warna
								<input name="warna" id="id_warna" type="color" required class="form-control" value="{{ selected_ruangan.warna }}" ng-model="warna" />
							</label>
							<span class="input-group-addon" style="font-size: 150%;color: red;padding-left: 15px">*</span>
						</div>
					</div>
				</div>

				<div class="form-group">
					<label for="id_restrict" class="control-label col-lg-3">Restrict Ruangan</label>
					<div class="col-lg-9">
						<div class="checkbox">
						  <label>
							  <input name="restrict" id="id_restrict" type="checkbox" {% if selected_ruangan.restricted %} checked="checked" {% endif %} >Ruangan disembunyikan <b style="color: red;padding-left: 5px">*</b>
						  </label>
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="col-lg-6 col-lg-offset-3">
                        <input type="submit" value="Save" class="btn btn-primary" >
                        <a href="{% url 'ruangan:index' %}" class="btn btn-default">Cancel</a>
                    </div>
                    <div class="col-lg-3" style="text-align: right">
                        <input type="button" value="Delete" class="btn btn-danger" onclick="javascript:window.location='{% url 'ruangan:delete' selected_ruangan.id %}';" />
                    </div>
				</div>

			</fieldset>
		</form>
	</div>
	<div class="col-lg-4">
        {% if error %}
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Error</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        {% for error_item in error %}
                        <li>{{ error_item }}</li>
                        {% endfor %}

                        {% for message_item in message %}
                        <li>{{ message_item }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

ruangan/templates/ruangan/index.html
{% extends "base.html" %}


{% block head %}
<title>Daftar ruangan</title>

<style>

	table, th , td {
		border: 1px solid grey;
		border-collapse: collapse;
		padding: 5px;
	}

	table th:hover {
		cursor: pointer;
	}
	
	table tr:nth-child(odd) {
		background-color: #f2f2f2;
	}

	table tr:nth-child(even) {
		background-color: #ffffff;
	}
   
	 
	.arrow-down:after,.arrow-up:after {
		content: ' ';
		position: relative;
		left: 2px;
		border: 8px solid transparent;
	}

	.arrow-down:after {
		top: 10px;
		border-top-color: black;
	}

	.arrow-up:after {
		bottom: 15px;
		border-bottom-color: black;
	}

	.arrow-down,.arrow-up {
		padding-right: 0px;
	}

</style>
{% endblock %}


{% block body %}
<script>
    var ruanganList = angular.module('ruanganList', []);
    ruanganList.config(function($interpolateProvider) {
  		$interpolateProvider.startSymbol('{[{');
  		$interpolateProvider.endSymbol('}]}');
	});
	ruanganList.controller("ruanganListController", function($scope) {
		
		$scope.ruanganListData = [];
		{% for ruangan in all_ruangan %}
		$scope.ruanganListData = $scope.ruanganListData.concat({
			id: "{{ ruangan.id }}",
			nama:"{{ ruangan.nama }}",
			harga:"{{ ruangan.harga }}",
			deskripsi:"{{ ruangan.deskripsi }}",
			tipe:"{{ ruangan.tipe }}",
			foto:"{{ ruangan.foto }}",
			warna:"{{ ruangan.warna }}",
			restricted:"{{ ruangan.restricted }}",
			edit_link: "{% url 'ruangan:edit' ruangan.id %}",
			delete_link: "{% url 'ruangan:delete' ruangan.id %}"
		});
		{% endfor %}

        $scope.go = function ( path ) {
            location.href = path;
        };

        //$scope.order = 'nama';

		// ORIGINAL CODE
		/*
        $scope.sort = function ( coll ) {
            if($scope.order == coll) {
                $scope.order = "-" + coll;
            } else {
                $scope.order = coll;
            }
        };
		*/
		
		
		/* EXPERIMENTAL CODE (Add arrow-down and arrow-up) */

		// column state
		$scope.column = 'nama';
		
		// sort ordering (Ascending or Descending). True for Descending
		$scope.reverse = false; 
		
		$scope.sort = function ( coll ) {
		
			$scope.column = coll;
		
			if ($scope.reverse) {
				$scope.reverse = false;
				$scope.reverseclass = 'arrow-up';
			} else {
				$scope.reverse = true;
				$scope.reverseclass = 'arrow-down';
			}
			
        };
		
		// change the arrow direction
		$scope.sortClass = function(col) {
			if ($scope.column == col) {
				if ($scope.reverse) {
					return 'arrow-down'; 
				} else {
					return 'arrow-up';
				}
			} else {
				return '';
			}
		}; 
 
	});
	$(document).ready(function () {
        $(".nav li").removeClass("active");
        $('#ruangan').addClass('active');
    });
</script>

<div ng-app="ruanganList" ng-controller="ruanganListController">
    <div class="row">
        <div class="col-sm-8">
            <ul class="breadcrumb" style="margin-bottom: 10px;">
                <li class="active">Ruangan</li>
            </ul>
        </div>
        <div class="col-sm-4" style="text-align: right">
            <a href="{% url 'ruangan:add' %}" class="btn btn-link btn-sm" style="padding-top: 8px">+ Tambah Ruangan</a>
        </div>
    </div>
    <div class="panel container-fluid">
	
		<!--
        <div class="row" style="margin-bottom: 10px">
            <div class="col-lg-offset-4 col-lg-6">
                <div class="form-group" style="text-align: right; margin-top: 10px">
                    <label for="id_tipe" class="control-label col-lg-3" style="text-align: right">Filter Type</label>
                    <div class="col-lg-3">
                        <select  ng-model="filterTipe" id="id_tipe" class="form-control input-sm">
                            <option value="" selected>Semua</option>
                            <option value="Ruang">Ruangan</option>
                            <option value="Lapangan">Lapangan</option>
                            <option value="Selasar">Selasar</option>
                        </select>
                    </div>
                    <label for="id_nama" class="control-label col-lg-3" style="text-align: right">Filter Name</label>
                    <div class="col-lg-3" style="text-align: right;padding: 0px;">
                        <input type="text" name="nama" id="id_nama" class="form-control input-sm" ng-model = "filterNama"/>
                    </div>
                </div>
            </div>
        </div>
		-->
		
		<!-- EXPERIMENT -->
		<div class="container-fluid" style="margin-bottom: 10px;margin-top: 10px">
            <div class="row well well-sm">
                
				<div class="form-group col-lg-2 col-md-6 col-sm-6">
                	<span><b>Filter Type</b></span>
                	<select ng-model="filterTipe" id="id_tipe" class="form-control input-sm">
						<option value="" selected>Semua</option>
						<option value="Ruang">Ruangan</option>
						<option value="Lapangan">Lapangan</option>
						<option value="Selasar">Selasar</option>
					</select>
				</div>
				<div class="form-group col-lg-2 col-md-6 col-sm-6">
                    <span><b>Filter Name</b></span>
                    <input type="text" name="nama" id="id_nama" class="form-control input-sm" ng-model = "filterNama"/>
                </div>
				
			</div>
		</div>
		<!-- END OF EXPERIMENT -->
		
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-bordered ">
                       
						<tr>
							<th ng-click="sort('nama')" ng-class="sortClass('nama')">Nama</th>
							<th ng-click="sort('harga')" ng-class="sortClass('harga')">Harga</th>
							<th ng-click="sort('deskripsi')" ng-class="sortClass('deskripsi')">Deskripsi</th>
							<th ng-click="sort('tipe')" ng-class="sortClass('tipe')">Tipe</th>
                            <th ng-click="sort('restricted')" ng-class="sortClass('restricted')">Tersembunyi</th>
							<th ng-click="sort('foto')" ng-class="sortClass('foto')">Foto</th>
						</tr>
					
						<tr ng-repeat = "ruanganData in ruanganListData | orderBy : column : reverse | filter:{tipe:filterTipe} | filter:{nama:filterNama}" >

							<td ng-click="go(ruanganData.edit_link)"><a href="#" style="color: {[{ruanganData.warna}]}">{[{ ruanganData.nama }]}</a></td>
							<td>{[{ ruanganData.harga }]}</td>
							<td>{[{ ruanganData.deskripsi }]}</td>
							<td>{[{ ruanganData.tipe }]}</td>
                            <td>{[{ ruanganData.restricted }]}</td>
                            <td>
                                <div class="square">
                                    <img data-toggle="modal" data-target="#modalFoto" data-img-source="/img/{[{ ruanganData.foto }]}" data-nama="{[{ ruanganData.nama }]}"
                                            ng-show="{[{ ruanganData.foto }]}" style="cursor: pointer" src="/img/{[{ ruanganData.foto }]}" alt="{[{ ruanganData.nama }]}" class="img-responsive">
                                </div>
                            </td>

						</tr>
                    </table>
                </div>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="modalFoto" role="dialog" tabindex="-1">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title" name="namaRuangan">Modal Header</h4>
                </div>
                <div class="modal-body">
                    <img src="" alt="" name="fotoRuangan" style="display: block; min-width: 0%; max-width: 100%; height: auto; margin: auto;">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
                </div>

            </div>
        </div>

        <style>
            @media screen and (min-width: 768px) { #modalFoto .modal-dialog { min-width: 25%; max-width: 75%; } }
            @media screen and (max-width: 767px) { #modalFoto .modal-dialog { min-width: 80%; max-width: 100%; align-self: center; } }
        </style>

        <script type="text/javascript">
            $('#modalFoto').on('show.bs.modal', function(e) {
                var src = $(e.relatedTarget).data('img-source');
                var name = $(e.relatedTarget).data('nama');
                $(e.currentTarget).find('h4[name="namaRuangan"]').text(name);
                $(e.currentTarget).find('img[name="fotoRuangan"]').attr('src', src);
                $(e.currentTarget).find('img[name="fotoRuangan"]').attr('alt', name);
            });
        </script>

        <ul>
        {% for error_item in error %}
        <li>{{ error_item }}</li>
        {% endfor %}

        {% for message_item in message %}
        <li>{{ message_item }}</li>
        {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}