PeminjamanRuanganSarpras/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^peminjam/', include('peminjam.urls')),
    url(r'^peminjaman/', include('peminjaman.urls')),
    url(r'^ruangan/', include('ruangan.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^login/$', auth_views.login, kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={'next_page': '/login/'}, name='logout'),
    url(r'^$', RedirectView.as_view(pattern_name='peminjaman:kalender_umum', permanent=False), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#    url(r'^admin/', admin.site.urls),

log/urls.py
from django.conf.urls import url
from . import views

app_name = 'log'

urlpatterns = [

    # /log/
    url(r'^$', views.index, name='index'),

    # /log/json/2016/
    url(r'^json/$', views.fetchrecord, name='jsonbase'),
    url(r'^json/(?P<start_year>[0-9]+)/$', views.fetchrecord, name='json'),

    # /log/filter/2017/1
    url(r'^filter/$', views.filter, name='filterbase'),
    url(r'^filter/(?P<select_year>[0-9]+)/(?P<select_month>[0-9]+)/', views.filter, name='filter'),
]

peminjam/urls.py
from django.conf.urls import url
from . import views

app_name = 'peminjam'

urlpatterns = [

    # /peminjam/
    url(r'^$', views.index, name='index'),

    # /peminjam/add/
    url(r'^add/$',views.formadd, name='add'),

    # /peminjam/edit/4
    url(r'^edit/$', views.formedit, name='editbase'),
    url(r'^edit/(?P<peminjam_id>[0-9]+)/$', views.formedit, name='edit'),

    # /peminjam/delete/4
    url(r'^delete/$', views.formdelete, name='deletebase'),
    url(r'^delete/(?P<peminjam_id>[0-9]+)/$', views.formdelete, name='delete'),

    # /peminjam/fetchjson/
    url(r'^json/$', views.fetchrecord, name='json'),
]

peminjam/models.py
from django.db import models

class Peminjam(models.Model):
    nama = models.CharField(max_length=250, unique=True, db_index=True)
    deskripsi = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return self.nama

peminjam/views.py
from django.shortcuts import render, redirect
from .models import Peminjam
from django.http import JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Peminjam index view, mostly for debugging purpose
@login_required
def index(request, message='', error=''):
    all_peminjam = Peminjam.objects.all()
    return render(request, 'peminjam/index.html', {
        'error': error,
        'message': message,
        'all_peminjam': all_peminjam
    })


# Return a form which'll be used to add new Peminjam object to model
@login_required
def formadd(request):

    # Inisiasi variabel berdasarkan post jika ada
    new_nama = request.POST.get("nama",'')
    new_deskripsi = request.POST.get("deskripsi",'')
    error = []
    message = []

    # Jika ada data post yang diberikan,
    if request.method == 'POST':

        # Mengecek apakah ada nama valid yang diberikan
        if new_nama == '':
            error += ["Nama organisasi tidak boleh kosong", ]

        # Mengecek apakah ada object dengan nama yang sama
        if (Peminjam.objects.filter(nama=new_nama)):
            error += ["Sudah ada data peminjam dengan nama yang sama", ]

        # Berusaha memasukan object ke database jika tidak ada error
        if not error:
            new_peminjam = Peminjam(
                nama=new_nama,
                deskripsi=new_deskripsi
            )

            # Berusaha menyimpan perubahan dan redirect ke Index jika berhasil
            try:
                new_peminjam.save()
            except Exception as e:
                message += ["Unhandled Exception", ]
            else:
                return redirect(reverse('peminjam:index'))

    # Mengembalikan form yang sama
    return render(request, 'peminjam/add.html', {
        'error': error,
        'message': message,
        'nama': new_nama,
        'deskripsi': new_deskripsi
    })


# Return a form which'll be used to edit Peminjam object to model
@login_required
def formedit(request, peminjam_id = 0):

    # Berusaha mendapat model peminjam yang ingin diubah
    try:
        selected_peminjam = Peminjam.objects.get(id=peminjam_id)
    except Exception as e:
        return redirect(reverse('peminjam:index'))

    # Inisiasi variabel berdasarkan post jika ada
    new_nama = request.POST.get("nama",selected_peminjam.nama)
    new_deskripsi = request.POST.get("deskripsi",selected_peminjam.deskripsi)
    error = []
    message = []

    # Jika ada data post yang diberikan,
    if request.method == 'POST':

        # Mengecek apakah ada nama valid yang diberikan
        if new_nama == '':
            error += ["Nama organisasi tidak boleh kosong", ]

        # Mengecek apakah ada object dengan nama yang sama
        if (Peminjam.objects.filter(nama=new_nama) and (not(selected_peminjam.nama == new_nama))):
            error += ["Sudah ada data peminjam dengan nama yang sama", ]

        # Berusaha mengubah informasi object jika tidak ada error
        if not error:
            selected_peminjam.nama = new_nama
            selected_peminjam.deskripsi = new_deskripsi

            # Berusaha menyimpan perubahan dan redirect ke Index jika berhasil
            try:
                selected_peminjam.save()
            except Exception as e:
                message += ["Unhandled Exception", ]
            else:
                return redirect(reverse('peminjam:index'))


    # Mengembalikan form yang sama
    return render(request, 'peminjam/edit.html', {
        'selected_peminjam': selected_peminjam,
        'error': error,
        'message': message,
    })


# Return a form which'll be used to delete Peminjam object to model
@login_required
def formdelete(request, peminjam_id = 0):

    # Berusaha mendapat model peminjam yang ingin diubah
    try:
        selected_peminjam = Peminjam.objects.get(id=peminjam_id)
    except Exception as e:
        return redirect(reverse('peminjam:index'))

    # Inisiasi variabel berdasarkan post jika ada
    new_nama = request.POST.get("nama",'')
    error = []
    message = []

    # Jika ada data post yang diberikan,
    if(new_nama):

        # Mengecek apakah ada object dengan nama yang sama
        if (not(selected_peminjam.nama == new_nama)):
            error += ["Nama peminjam tidak sama", ]

        # Berusaha mengubah informasi object jika tidak ada error
        if not error:

            # Berusaha menyimpan perubahan dan redirect ke Index jika berhasil
            try:
                selected_peminjam.delete()
            except Exception as e:
                message += ["Unhandled Exception", ]
            else:
                return redirect(reverse('peminjam:index'))

    # Mengembalikan form yang sama
    return render(request, 'peminjam/delete.html', {
        'selected_peminjam': selected_peminjam,
        'error': error,
        'message': message,
    })


def fetchrecord(request):
    all_peminjam = Peminjam.objects.all().values()
    return JsonResponse({'results': list(all_peminjam)})

peminjam/templates/peminjam/add.html
{% extends "base.html" %}

{% block head %}
<title>Menambahkan Peminjam Baru</title>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-8">
        <ul class="breadcrumb" style="margin-bottom: 10px;">
            <li><a href="{% url 'peminjam:index' %}">Peminjam</a></li>
            <li class="active">Tambah Peminjam</li>
        </ul>
    </div>
</div>
<div class="container-fluid">
<div class="row">
    <div class="col-lg-6 panel ">
        <form action="{% url 'peminjam:add' %}" method="post" class="form-horizontal">
            {% csrf_token %}

            <fieldset>
                <legend style="padding-top: 15px;margin-bottom: 15px">Formulir Penambahan Peminjam</legend>
                <p style="color: red;text-align: right">* wajib diisi</p>
                <div class="form-group">
                    <label for="id_nama" class="col-lg-3 control-label">Nama</label>
                    <div class="col-lg-9">
                        <div class="input-group">
                            <input type="text" name="nama" id="id_nama" required value="{{ nama }}" maxlength="250" class="form-control"/>
                            <span class="input-group-addon" style="font-size: 150%;color: red">*</span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
					<label for="id_deskripsi" class="control-label col-lg-3">Deskripsi</label>
					<div class="col-md-9">
						<textarea name="deskripsi" id="id_deskripsi" maxlength="1000" class="form-control">{{ deskripsi }}</textarea>
					</div>
				</div>
                
                <div class="form-group">
					<div class="col-lg-10 col-lg-offset-2" style="text-align: right">
						<input type="submit" value="Save" class="btn btn-primary"/>
                        <a href="{% url 'peminjam:index' %}" class="btn btn-default">Cancel</a>
					</div>
				</div>

            </fieldset>
        </form>
    </div>
    <div class="col-lg-4">
        {% if error %}
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Error</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        {% for error_item in error %}
                        <li>{{ error_item }}</li>
                        {% endfor %}

                        {% for message_item in message %}
                        <li>{{ message_item }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

peminjam/templates/peminjam/delete.html
{% extends "base.html" %}

{% block head %}
<title>Menghapus Data Peminjam</title>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-8">
        <ul class="breadcrumb" style="margin-bottom: 10px;">
            <li><a href="{% url 'peminjam:index' %}">Peminjam</a></li>
            <li class="active">Hapus Peminjam</li>
        </ul>
    </div>
</div>
<div class="container-fluid">
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Harap Perhatian!</h3>
            </div>
            <div class="panel-body">

                <p>Anda akan menghapus data peminjam berikut ini: </p>
                <table class="table table-striped table-hover ">
                  <thead>
                    <tr>
                      <th>Nama</th>
                      <th>Deskripsi</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>{{ selected_peminjam.nama }}</td>
                      <td>{{ selected_peminjam.deskripsi }}</td>
                    </tr>
                  </tbody>
                </table>
                <p>Dengan menghapus data peminjam, maka
                    <span style="color: red">SEMUA DATA TERKAIT PEMINJAM INI JUGA AKAN DIHAPUS</span>.
                 Harap berhati-hati.
                </p>
                <p>Untuk menghapus, harap ketik ulang nama peminjam pada field di bawah.</p>
                <form action="{% url 'peminjam:delete' selected_peminjam.id %}" method="post">

                    {% csrf_token %}
                    <div class="input-group col-sm-6">
                        <input type="text" name="nama" class="form-control input-sm" autofocus required>
                        <div class="input-group-btn">
                            <input type="submit" value="Delete" class="btn btn-default btn-sm">
                        </div>
                    </div>
                    {% for error_item in error %}
                    <span>{{ error_item }}</span>
                    {% endfor %}

                    {% for message_item in message %}
                    <span>{{ message_item }}</span>
                    {% endfor %}
                    <div style="text-align: right;padding-top: 20px">
                        <a href="{% url 'peminjam:index' %}" class="btn btn-primary">Cancel</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

peminjam/templates/peminjam/edit.html
{% extends "base.html" %}

{% block head %}
<title>Mengubah Informasi Peminjam</title>
{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-8">
        <ul class="breadcrumb" style="margin-bottom: 10px;">
            <li><a href="{% url 'peminjam:index' %}">Peminjam</a></li>
            <li class="active">Ubah Peminjam</li>
        </ul>
    </div>
</div>
<div class="container-fluid">
<div class="row">
    <div class="col-lg-6 panel ">
        <form action="{% url 'peminjam:edit' selected_peminjam.id %}" method="post" class="form-horizontal">
            {% csrf_token %}

            <fieldset>
                <legend style="padding-top: 15px;margin-bottom: 15px">Formulir Perubahan Peminjam</legend>
                <p style="color: red;text-align: right">* wajib diisi</p>
                <div class="form-group">
                    <label for="id_nama" class="col-lg-3 control-label">Nama</label>
					<div class="col-lg-9">
						<div class="input-group">
							<input type="text" name="nama" id="id_nama" required value="{{ selected_peminjam.nama }}" maxlength="250" class="form-control"/>
							<span class="input-group-addon" style="font-size: 150%;color: red">*</span>
						</div>
					</div>
                </div>

                <div class="form-group">
					<label for="id_deskripsi" class="control-label col-lg-3">Deskripsi</label>
					<div class="col-md-9">
						<textarea name="deskripsi" id="id_deskripsi" maxlength="1000" class="form-control">{{ selected_peminjam.deskripsi }}</textarea>
					</div>
				</div>
                <div class="form-group">
					<div class="col-lg-6 col-lg-offset-3">
                        <input type="submit" value="Save" class="btn btn-primary" >
                        <a href="{% url 'peminjam:index' %}" class="btn btn-default">Cancel</a>
                    </div>
                    <div class="col-lg-3" style="text-align: right">
                        <input type="button" value="Delete" class="btn btn-danger" onclick="javascript:window.location='{% url 'peminjam:delete' selected_peminjam.id %}';" />
					</div>
				</div>
            </fieldset>
        </form>
    </div>
    <div class="col-lg-4">
        {% if error %}
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h3 class="panel-title">Error</h3>
                </div>
                <div class="panel-body">
                    <ul>
                        {% for error_item in error %}
                        <li>{{ error_item }}</li>
                        {% endfor %}

                        {% for message_item in message %}
                        <li>{{ message_item }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
</div>
</div>
{% endblock %}

peminjam/templates/peminjam/index.html
{% extends "base.html" %}


{% block head %}
<title>Daftar Peminjam</title>

<style>

	table th:hover {
		cursor: pointer;
	}
	
	.arrow-down:after,.arrow-up:after {
		content: ' ';
		position: relative;
		left: 2px;
		border: 8px solid transparent;
	}

	.arrow-down:after {
		top: 10px;
		border-top-color: black;
	}

	.arrow-up:after {
		bottom: 15px;
		border-bottom-color: black;
	}

	.arrow-down,.arrow-up {
		padding-right: 0px;
	}

</style>

{% endblock %}


{% block body %}
<script>
    var peminjamList = angular.module('peminjamList', []);
    peminjamList.config(function($interpolateProvider) {
  		$interpolateProvider.startSymbol('{[{');
  		$interpolateProvider.endSymbol('}]}');
	});
	peminjamList.controller("peminjamListController", function($scope, $location) {
		
		$scope.peminjamListData = [];
		{% for peminjam in all_peminjam %}
		$scope.peminjamListData = $scope.peminjamListData.concat({
			id: "{{ peminjam.id }}",
			nama:"{{ peminjam.nama }}",
			deskripsi:"{{ peminjam.deskripsi }}",
			edit_link: "{% url 'peminjam:edit' peminjam.id %}"
		});
		{% endfor %}

		$scope.go = function ( path ) {
            location.href = path;
        };

		/* ORIGINAL CODE
        $scope.order = 'id';
        $scope.sort = function ( coll ) {
            if($scope.order == coll) {
                $scope.order = "-" + coll;
            } else {
                $scope.order = coll;
            }
        };
		*/
		
		/* EXPERIMENTAL CODE (Add arrow-down and arrow-up) */
		
		// column state
		$scope.column = 'id';
		
		// sort ordering (Ascending or Descending). True for Descending
		$scope.reverse = false; 
		
		$scope.sort = function ( coll ) {
		
			$scope.column = coll;
		
			if ($scope.reverse) {
				$scope.reverse = false;
				$scope.reverseclass = 'arrow-up';
			} else {
				$scope.reverse = true;
				$scope.reverseclass = 'arrow-down';
			}
			
        };
		
		// change the arrow direction
		$scope.sortClass = function(col) {
			if ($scope.column == col) {
				if ($scope.reverse) {
					return 'arrow-down'; 
				} else {
					return 'arrow-up';
				}
			} else {
				return '';
			}
		};

	});
	$(document).ready(function () {
        $(".nav li").removeClass("active");
        $('#peminjam').addClass('active');
    });
</script>

<div ng-app="peminjamList" ng-controller="peminjamListController">
    <div class="row">
        <div class="col-sm-8">
            <ul class="breadcrumb" style="margin-bottom: 10px;">
                <li class="active">Peminjam</li>
            </ul>
        </div>
        <div class="col-sm-4" style="text-align: right">
            <a href="{% url 'peminjam:add' %}" class="btn btn-link btn-sm" style="padding-top: 8px">+ Tambah Peminjam</a>
        </div>
    </div>
    <div class="panel container-fluid">

		<!-- EXPERIMENT -->
		<div class="container-fluid" style="margin-bottom: 10px;margin-top: 10px">
            <div class="row well well-sm">
                
				<div class="form-group col-lg-2 col-md-6 col-sm-12">
                	<span><b>Filter Nama</b></span>
					<input type="text" name="nama" id="id_nama" class="form-control input-sm" ng-model = "filterNama"/>
                </div>
				
			</div>
		</div>
		<!-- END OF EXPERIMENT -->
		
		
        <div class="row">
            <div class="col-lg-10">
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                            <tr>
                                <th ng-click="sort('nama')" ng-class="sortClass('nama')">Nama</th>
                                <th ng-click="sort('deskripsi')" ng-class="sortClass('deskripsi')">Deskripsi</th>
                            </tr> 
                        </thead>
                        <tbody>
							<tr ng-repeat = "peminjamData in peminjamListData | orderBy : column : reverse | filter:{id:filterId} | filter:{nama:filterNama}">

                                <td ng-click="go(peminjamData.edit_link)"><a href="#">{[{ peminjamData.nama }]}</a></td>
                               <td>{[{ peminjamData.deskripsi }]}</td>
							
							</tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


<ul>
    {% for error_item in error %}
        <li>{{ error_item }}</li>
    {% endfor %}

    {% for message_item in message %}
        <li>{{ message_item }}</li>
    {% endfor %}
</ul>

</div>

{% endblock %}