PeminjamanRuanganSarpras/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^peminjam/', include('peminjam.urls')),
    url(r'^peminjaman/', include('peminjaman.urls')),
    url(r'^ruangan/', include('ruangan.urls')),
    url(r'^log/', include('log.urls')),
    url(r'^login/$', auth_views.login, kwargs={'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, kwargs={'next_page': '/login/'}, name='logout'),
    url(r'^$', RedirectView.as_view(pattern_name='peminjaman:kalender_umum', permanent=False), name='index'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#    url(r'^admin/', admin.site.urls),

log/urls.py
from django.conf.urls import url
from . import views

app_name = 'log'

urlpatterns = [

    # /log/
    url(r'^$', views.index, name='index'),

    # /log/json/2016/
    url(r'^json/$', views.fetchrecord, name='jsonbase'),
    url(r'^json/(?P<start_year>[0-9]+)/$', views.fetchrecord, name='json'),

    # /log/filter/2017/1
    url(r'^filter/$', views.filter, name='filterbase'),
    url(r'^filter/(?P<select_year>[0-9]+)/(?P<select_month>[0-9]+)/', views.filter, name='filter'),
]

peminjaman/urls.py
from django.conf.urls import url
from . import views

app_name = 'peminjaman'

urlpatterns = [

    # /peminjaman/
    url(r'^$', views.index, name='index'),

    # /peminjaman/kalender
    url(r'^kalender/$', views.kalender, name='kalender'),
    url(r'^kalender-umum/$', views.kalender_umum, name='kalender_umum'),

    # /peminjaman/add/
    url(r'^add/$',views.formadd, name='add'),

    # /peminjaman/edit/4
    url(r'^edit/$', views.formedit, name='editbase'),
    url(r'^edit/(?P<peminjaman_id>[0-9]+)/$', views.formedit, name='edit'),

    # /peminjaman/delete/4
    url(r'^delete/$', views.formdelete, name='deletebase'),
    url(r'^delete/(?P<peminjaman_id>[0-9]+)/$', views.formdelete, name='delete'),

    # /peminjaman/json/2016
    url(r'^json/$', views.fetchrecord, name='jsonbase'),
    url(r'^json/(?P<start_year>[0-9]+)/$', views.fetchrecord, name='json'),

    # /peminjaman/json_umum/2016
    url(r'^json_umum/$', views.fetchrecord_umum, name='jsonbase_umum'),
    url(r'^json_umum/(?P<start_year>[0-9]+)/$', views.fetchrecord_umum, name='json_umum'),

    # /peminjaman/bayar/2
    url(r'^bayar/$', views.togglepembayaran, name='bayarbase'),
    url(r'^bayar/(?P<peminjaman_id>[0-9]+)/$', views.togglepembayaran, name='bayar'),

    #/peminjaman/filter/2017
    url(r'^filter/$', views.filter, name='filter_base'),
    url(r'^filter/(?P<year>[0-9]+)/$', views.filter, name='filter'),
]

log/models.py
from django.db import models
from peminjaman.models import Peminjaman
from datetime import date

class Log(models.Model):
    peminjaman = models.ForeignKey(Peminjaman, blank=True, null=True, on_delete=models.SET_NULL)
    peminjaman_str = models.CharField(blank=True, max_length=500)
    tanggal = models.DateField(auto_now_add=True, db_index=True)
    deskripsi = models.CharField(blank=True, max_length=1000) #Bernilai deskripsi yang akan ditunjukan apabila object peminjaman sudah dihapus

    CREATE = 'Buat'
    UPDATE = 'Ubah'
    DELETE = 'Hapus'
    PILIHAN_TIPE_AKSI = (
        (CREATE, 'Buat'),
        (UPDATE, 'Ubah'),
        (DELETE, 'Hapus'),
    )
    aksi = models.CharField(max_length=50, choices=PILIHAN_TIPE_AKSI, default=UPDATE)

log/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import Log
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Log index view
@login_required
def index(request):
    all_log = Log.objects.all()
    return render(request, 'log/index.html', {
        'all_log': all_log,
    })

#Ajax Bulan dan tahun
@login_required
@csrf_exempt
def filter(request, select_year,select_month):
    if select_year == "1971" and select_month == "0":
        selected_log = Log.objects.values()
    elif select_month == "0":
        selected_log = Log.objects.filter(tanggal__year=select_year).values()
    else:
        selected_log = Log.objects.filter(tanggal__year=select_year, tanggal__month=select_month).values()
    return JsonResponse({'results': list(selected_log)})

@login_required
def fetchrecord(request, start_year = 2017):
    selected_log = Log.objects.filter(tanggal__year = start_year).values()
    return JsonResponse({'results': list(selected_log)})

log/templates/log/index.html
{% extends "base.html" %}


{% block head %}
<title>Log Perubahan Data Peminjaman</title>

<style>

	table th:hover {
		cursor: pointer;
	}

	.arrow-down:after,.arrow-up:after {
		content: ' ';
		position: relative;
		left: 2px;
		border: 8px solid transparent;
	}

	.arrow-down:after {
		top: 10px;
		border-top-color: black;
	}

	.arrow-up:after {
		bottom: 15px;
		border-bottom-color: black;
	}

	.arrow-down,.arrow-up {
		padding-right: 0px;
	}

	.control-label {
		margin-top: 2px;
		padding-left: 50px;
	}

</style>

{% endblock %}


{% block body %}

<!--
<legend>Log Perubahan Data Peminjaman</legend>
-->

<script>
    var logList = angular.module('logList', []);
    logList.config(function($interpolateProvider) {
  		$interpolateProvider.startSymbol('{[{');
  		$interpolateProvider.endSymbol('}]}');
	});
	logList.controller("logListController", function($scope, $http) {
		var aksi = [];
		$scope.aksiListData = [];
		$scope.aksiListData = $scope.aksiListData.concat({
          string: "Buat",
    });
		$scope.aksiListData = $scope.aksiListData.concat({
	        string: "Ubah",
	    });

			$scope.filterTimeStart = new Date();
			$scope.filterTimeStart.setMonth(0);
			$scope.filterTimeStart.setDate(1);

			$scope.filterTimeEnd = new Date();
			$scope.filterTimeEnd.setMonth(0);
			$scope.filterTimeEnd.setDate(1);
			$scope.filterTimeEnd.setFullYear(1+$scope.filterTimeStart.getFullYear());

		$scope.logListData = [];

		$scope.fetchLog = function(year) {
            var url = "{% url 'log:jsonbase' %}" + year
            $http.get(url).success(function(data, status, headers, config) {
                var temp = data.results;
                angular.forEach(temp, function(value, key){

                    $scope.logListData = $scope.logListData.concat({
                        tanggal:        new Date(value.tanggal),
                        peminjaman_str: value.peminjaman_str,
                        aksi:           value.aksi,
                        deskripsi:      value.deskripsi,
                    });
                });
            }).error(function(data, status, headers, config) {
                $scope.logListData = "ERROR";
            });
        };

        $scope.fetchLog(new Date().getFullYear());

        $scope.openPeminjaman = function ( logItem ) {
            if(angular.isUndefined(logItem.peminjaman_id) || logItem.peminjaman_id === null) {
                window.alert("Peminjaman yang terkait telah dihapus dari sistem");
            } else {
                location.href = "{% url 'peminjaman:editbase' %}" + logItem.peminjaman_id;
            }
        };

		/* ORIGINAL CODE
        $scope.order = 'tanggal';
        $scope.sort = function ( coll ) {
            if($scope.order == coll) {
                $scope.order = "-" + coll;
            } else {
                $scope.order = coll;
            }
        };
		*/

		/* EXPERIMENTAL CODE (Add arrow-down and arrow-up) */
		// Fungsi pemunculan list tanggal
        var year = new Date().getFullYear();
        var range = [];
        range.push(year);
        for(var i=1;i<20;i++) {
          range.push(year - i);
        }
        $scope.years = range;

        $scope.filterlog = function ( tahun,bulan) {
          if(((typeof tahun === 'undefined' ) || (tahun == null)) || (tahun == ""))
          {
            tahun = "1971";
          }
          if(((typeof bulan === 'undefined'  ) || (bulan == null)) || (bulan == ""))
          {
            bulan = "0";
          }
          var req = {
            method: 'GET',
            url: "{% url 'log:filterbase' %}" + tahun + "/" + bulan + "/"
          }
          $http.get(req.url).success(function(data, status, headers, config) {
              var temp = data.results;
              $scope.logListData = [];
              angular.forEach(temp, function(value, key){

                  $scope.logListData = $scope.logListData.concat({
                      tanggal:        new Date(value.tanggal),
                      peminjaman_str: value.peminjaman_str,
                      aksi:           value.aksi,
                      deskripsi:      value.deskripsi,
                  });
              });
          }).error(function(data, status, headers, config) {
              $scope.logListData = "ERROR";
          });
        }


		// column state
		$scope.column = 'tanggal';

		// sort ordering (Ascending or Descending). True for Descending
		$scope.reverse = false;

		$scope.sort = function ( coll ) {

			$scope.column = coll;

			if ($scope.reverse) {
				$scope.reverse = false;
				$scope.reverseclass = 'arrow-up';
			} else {
				$scope.reverse = true;
				$scope.reverseclass = 'arrow-down';
			}

		};

		// change the arrow direction
		$scope.sortClass = function(col) {
			if ($scope.column == col) {
				if ($scope.reverse) {
					return 'arrow-down';
				} else {
					return 'arrow-up';
				}
			} else {
				return '';
			}
		};

	});
	$(document).ready(function () {
        $(".nav li").removeClass("active");
        $('#log').addClass('active');
    });
</script>

<div ng-app="logList" ng-controller="logListController">
	<div class="row">
        <div class="col-sm-8">
            <ul class="breadcrumb" style="margin-bottom: 10px;">
                <li class="active">Log Perubahan Data Peminjaman</li>
            </ul>
        </div>
    </div>

    <div class="panel container-fluid">
		<!--
		<div class="col-lg-10" style="margin-top: 10px;margin-bottom: 10px;">
			<div class="form-group">
				<label class="control-label col-lg-2" for="id_filter_tahun">Filter Tahun</label>
				<div class="col-lg-2" style="padding: 0px">
					<select ng-model="filterTahun" id="id_filter_tahun" class="form-control input-sm">
						<option value="" selected>Semua</option>
					</select>
				</div>

				<label class="control-label col-lg-2" for="id_filter_bulan">Filter Bulan</label>
				<div class="col-lg-2" style="padding: 0px">
					<select ng-model="filterBulan" id="id_filter_bulan" class="form-control input-sm">
						<option value="" selected>Semua</option>
					</select>
				</div>

				<label class="control-label col-lg-2" for="id_filter_aksi">Filter Aksi</label>
				<div class="col-lg-2" style="padding: 0px">
					<select ng-model="filterAksi" id="id_filter_aksi" class="form-control input-sm">
						<option value="" selected>Semua</option>
						<option value="{[{ aksiData.string }]}" ng-repeat = "aksiData in aksiListData ">{[{ aksiData.string }]}</option>
					</select>
				</div>
			</div>
		</div>
		-->
	
		<!-- EXPERIMENT -->
		<div class="container-fluid" style="margin-bottom: 10px;margin-top: 10px">
            <div class="row well well-sm">
                
				<div class="form-group col-lg-2 col-md-6 col-sm-4">
                	<span><b>Filter Tahun</b></span>
                	<select ng-options="year for year in years" ng-change="filterlog(filterTahun,filterBulan)" style="text-align: right;" ng-model="filterTahun" id="id_filter_tahun" class="form-control input-sm">
						<option value="" selected>Semua</option>
					</select>
                </div>
				<div class="form-group col-lg-2 col-md-6 col-sm-4">
                    <span><b>Filter Bulan</b></span>
                    <select ng-change="filterlog(filterTahun,filterBulan)" ng-model="filterBulan" id="id_filter_bulan" class="form-control input-sm">
						<option value="" selected>Semua</option>
						<option value="1">Januari</option>
						<option value="2">Febuari</option>
						<option value="3">Maret</option>
						<option value="4">April</option>
						<option value="5">Mei</option>
						<option value="6">Juni</option>
						<option value="7">Juli</option>
						<option value="8">Agustus</option>
						<option value="9">September</option>
						<option value="10">Oktober</option>
						<option value="11">November</option>
						<option value="12">Desember</option>
					</select>
                </div>
                <div class="form-group col-lg-2 col-md-6 col-sm-4">
                    <span><b>Filter Aksi</b></span>
                    <select ng-change="filterlog(filterTahun,filterBulan)" style="text-align: right;" ng-model="filterAksi" id="id_filter_aksi" class="form-control input-sm">
						<option value="" selected>Semua</option>
						<option value="{[{ aksiData.string }]}" ng-repeat = "aksiData in aksiListData ">{[{ aksiData.string }]}</option>
					</select>
                </div>				
			</div>
		</div>
		<!-- END OF EXPERIMENT -->
		
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table table-striped table-hover table-bordered">
                    <thead>
                        <tr>
                            <th class="col-lg-2" ng-click="sort('tanggal')" ng-class="sortClass('tanggal')">Tanggal</th>
                            <th class="col-lg-5" ng-click="sort('peminjaman_str')" ng-class="sortClass('peminjaman_str')">Peminjaman</th>
                            <th class="col-lg-1" ng-click="sort('aksi')" ng-class="sortClass('aksi')">Aksi</th>
                            <th ng-click="sort('deskripsi')" ng-class="sortClass('deskripsi')">Deskripsi</th>
                        </tr>
                    </thead>
                    <tbody>
                       <tr ng-repeat = "logData in logListData | orderBy : column : reverse | filter:{aksi:filterAksi} | filter: inRange(toTimestamp(filterTimeStart),toTimestamp(filterTimeEnd))  ">
                           <td>{[{ logData.tanggal | date:'dd MMM yyyy' : 'UTC' }]}</td>
                           <td ng-click="openPeminjaman(logData)">{[{ logData.peminjaman_str }]}</td>
                           <td>{[{ logData.aksi }]}</td>
                           <td><pre>{[{ logData.deskripsi }]}</pre></td>
                       </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}